import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "../components/TopNav";
import { SessionProvider } from "next-auth/react";
import { ToastProvider } from "../components/ToastProvider";
import { ErrorBoundary } from "../components/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500`}
        tabIndex={0}
      >
        <a href="#main-content" className="sr-only focus:not-sr-only absolute top-2 left-2 bg-blue-700 text-white px-3 py-1 rounded z-[1001]">
          Skip to main content
        </a>
        <SessionProvider>
          <ToastProvider>
            <ErrorBoundary>
              <TopNav />
              <div id="main-content" style={{ paddingTop: 56 }}>
                {children}
              </div>
            </ErrorBoundary>
          </ToastProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
